name: Code quality

on: pull_request

concurrency:
  group: ${{ env.GITHUB_HEAD_REF }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: nix-flakes

    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: |
          nix develop . --command cargo clippy -- -Dwarnings
