name: Code quality

on: pull_request

concurrency:
  group: ${{ gitea.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: nix-flakes

    steps:
      - name: Set up packages
        run: |
          echo "extra-substituters = https://builder.naxdy.org/attic" >> /etc/nix/nix.conf
          echo "extra-trusted-public-keys = attic:05LdE8Nav5Qd1E+KOJqSwdr+WE1z8AUmSb3oKL7s8dk=" >> /etc/nix/nix.conf
          nix profile install nixpkgs#nodejs "github:zhaofengli/attic?ref=6eabc3f02fae3683bffab483e614bebfcd476b21"
          echo "PATH=/nix/var/nix/profiles/per-user/root/profile/bin:$PATH" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: |
          nix develop . --command cargo clippy -- -Dwarnings 
