name: Publish nightly release

on:
  push:
    branches: ["main"]

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  build:
    runs-on: nix-flakes

    steps:
      - name: Set up attic binary cache
        uses: https://git.naxdy.org/NaxdyOrg/attic-action@v0.3
        with:
          endpoint: "${{ vars.BINARY_CACHE_URL }}"
          token: "${{ secrets.PUBLIC_BINARY_CACHE_AUTH_KEY }}"
          cache: "${{ vars.PUBLIC_BINARY_CACHE_NAME }}"
      - uses: actions/checkout@v4

      - name: Run flake checks
        run: |
          nix flake check . --print-build-logs -j auto

      - name: Build firmware image
        run: |
          nix build .# -o dist --print-build-logs

      - name: (Re-)generate tag
        run: |
          git config --global user.email "noreply@naxdy.org"
          git config --global user.name "Naxbot"
          git fetch --tags
          git tag -d nightly || true
          git tag nightly -m "Nightly Release"
          git checkout nightly
          git push --set-upstream origin nightly --force

      - name: Publish nightly release
        uses: https://gitea.com/actions/gitea-release-action@v1.3.0
        with:
          token: "${{ github.token }}"
          tag_name: nightly
          prerelease: true
          name: "Nightly Release"
          body: >
            This is an automatically generated nightly release, based on the current state of the `main` branch.

            **WARNING:** This release may contain untested changes and could potentially break your configuration. Use at your own risk. **Do not report issues you encounter with nightly releases.**
          files: |
            dist/bin/*
