name: Publish stable release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: nix-flakes

    steps:
      - name: Set up attic binary cache
        uses: https://git.naxdy.org/NaxdyOrg/attic-action@v0.3
        with:
          endpoint: "${{ vars.BINARY_CACHE_URL }}"
          token: "${{ secrets.PUBLIC_BINARY_CACHE_AUTH_KEY }}"
          cache: "${{ vars.PUBLIC_BINARY_CACHE_NAME }}"
      - uses: actions/checkout@v4
      - name: Build firmware image
        run: |
          nix build .# -o dist --print-build-logs
      - name: Publish stable release
        uses: https://gitea.com/actions/gitea-release-action@v1.3.0
        with:
          token: "${{ github.token }}"
          tag_name: "${{ env.GITHUB_REF_NAME }}"
          name: "NaxGCC ${{ env.GITHUB_REF_NAME }}"
          body_path: .changelogs/${{ env.GITHUB_REF_NAME }}.md
          files: |
            dist/bin/*
